"""20 evidence templates linked to control templates."""

EVIDENCE_TEMPLATES = [
    {
        "template_code": "EV-001",
        "title": "MFA Enrollment Report",
        "description": "Report showing MFA enrollment status for all active users.",
        "evidence_type": "report",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"columns": ["user_email", "mfa_enabled", "mfa_method", "last_mfa_use"]},
        "pass_criteria": {"min_enrollment_rate": 100},
        "integrations": {"sources": ["identity_provider"]},
        "control_template_codes": ["AC-001"],
    },
    {
        "template_code": "EV-002",
        "title": "SSO Configuration Screenshot",
        "description": "Screenshot or export of SSO configuration showing integrated applications.",
        "evidence_type": "screenshot",
        "format": "png",
        "collection_method": "manual",
        "refresh_frequency": "quarterly",
        "retention_period": "1 year",
        "fields": {"sections": ["provider_config", "integrated_apps", "session_policy"]},
        "pass_criteria": {"all_critical_apps_integrated": True},
        "integrations": {"sources": ["identity_provider"]},
        "control_template_codes": ["AC-002"],
    },
    {
        "template_code": "EV-003",
        "title": "User Access List",
        "description": "Complete list of users with their roles and access rights across systems.",
        "evidence_type": "report",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "quarterly",
        "retention_period": "1 year",
        "fields": {"columns": ["user_email", "role", "systems", "last_access", "manager"]},
        "pass_criteria": {"no_orphaned_accounts": True},
        "integrations": {"sources": ["identity_provider", "cloud_iam"]},
        "control_template_codes": ["AC-003", "AC-005"],
    },
    {
        "template_code": "EV-004",
        "title": "Access Review Completion Evidence",
        "description": "Documentation showing quarterly access review was completed with manager approvals.",
        "evidence_type": "document",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "quarterly",
        "retention_period": "2 years",
        "fields": {"sections": ["review_period", "reviewer", "findings", "remediations"]},
        "pass_criteria": {"review_completed": True, "all_findings_addressed": True},
        "integrations": {},
        "control_template_codes": ["AC-005"],
    },
    {
        "template_code": "EV-005",
        "title": "Firewall Rules Export",
        "description": "Export of current firewall rules and security group configurations.",
        "evidence_type": "config",
        "format": "json",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"sections": ["inbound_rules", "outbound_rules", "security_groups"]},
        "pass_criteria": {"no_unrestricted_inbound": True, "default_deny_egress": True},
        "integrations": {"sources": ["cloud_provider"]},
        "control_template_codes": ["NS-001"],
    },
    {
        "template_code": "EV-006",
        "title": "TLS Certificate Report",
        "description": "Report of TLS certificates on all public-facing endpoints with expiry dates.",
        "evidence_type": "report",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"columns": ["domain", "issuer", "version", "cipher_suite", "expiry_date"]},
        "pass_criteria": {"min_tls_version": "1.2", "no_expired_certs": True},
        "integrations": {"sources": ["certificate_manager", "tls_scanner"]},
        "control_template_codes": ["NS-002"],
    },
    {
        "template_code": "EV-007",
        "title": "Encryption at Rest Configuration",
        "description": "Configuration evidence showing encryption is enabled on all storage services.",
        "evidence_type": "config",
        "format": "json",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"sections": ["s3_encryption", "rds_encryption", "ebs_encryption", "kms_keys"]},
        "pass_criteria": {"all_storage_encrypted": True, "key_rotation_enabled": True},
        "integrations": {"sources": ["cloud_provider"]},
        "control_template_codes": ["DP-001"],
    },
    {
        "template_code": "EV-008",
        "title": "Backup Status Report",
        "description": "Report showing backup job status, success rates, and last successful backup times.",
        "evidence_type": "report",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "weekly",
        "retention_period": "1 year",
        "fields": {"columns": ["resource", "last_backup", "status", "size", "retention_compliant"]},
        "pass_criteria": {"min_success_rate": 99, "all_resources_backed_up": True},
        "integrations": {"sources": ["cloud_provider", "backup_service"]},
        "control_template_codes": ["DP-003"],
    },
    {
        "template_code": "EV-009",
        "title": "Backup Restoration Test Results",
        "description": "Documentation of quarterly backup restoration test with results.",
        "evidence_type": "document",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "quarterly",
        "retention_period": "2 years",
        "fields": {"sections": ["test_date", "resources_tested", "rto_achieved", "rpo_achieved", "issues"]},
        "pass_criteria": {"test_successful": True, "rto_met": True},
        "integrations": {},
        "control_template_codes": ["DP-003"],
    },
    {
        "template_code": "EV-010",
        "title": "Pull Request Review Evidence",
        "description": "Report of merged pull requests showing review approvals.",
        "evidence_type": "report",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"columns": ["pr_number", "author", "reviewers", "approved", "merged_at"]},
        "pass_criteria": {"all_prs_reviewed": True, "no_self_approvals": True},
        "integrations": {"sources": ["github", "gitlab"]},
        "control_template_codes": ["CM-002"],
    },
    {
        "template_code": "EV-011",
        "title": "CI/CD Pipeline Configuration",
        "description": "Export of CI/CD pipeline configuration showing security gates and checks.",
        "evidence_type": "config",
        "format": "yaml",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"sections": ["pipeline_stages", "security_checks", "deployment_gates"]},
        "pass_criteria": {"sast_enabled": True, "sca_enabled": True, "tests_required": True},
        "integrations": {"sources": ["github_actions", "gitlab_ci"]},
        "control_template_codes": ["CM-003"],
    },
    {
        "template_code": "EV-012",
        "title": "Centralized Log Configuration",
        "description": "Configuration evidence showing all systems shipping logs to centralized logging.",
        "evidence_type": "config",
        "format": "json",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"sections": ["log_sources", "retention_config", "integrity_controls"]},
        "pass_criteria": {"all_systems_logging": True, "retention_compliant": True},
        "integrations": {"sources": ["cloud_provider", "siem"]},
        "control_template_codes": ["LM-001"],
    },
    {
        "template_code": "EV-013",
        "title": "Security Alert Rules",
        "description": "Export of configured security alerting rules and escalation procedures.",
        "evidence_type": "config",
        "format": "json",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"sections": ["alert_rules", "notification_channels", "escalation_matrix"]},
        "pass_criteria": {"critical_alerts_configured": True, "on_call_active": True},
        "integrations": {"sources": ["siem", "pagerduty"]},
        "control_template_codes": ["LM-002"],
    },
    {
        "template_code": "EV-014",
        "title": "Vulnerability Scan Report",
        "description": "Latest vulnerability scan results with severity breakdown and remediation status.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "automated",
        "refresh_frequency": "weekly",
        "retention_period": "1 year",
        "fields": {"sections": ["scan_summary", "critical_vulns", "high_vulns", "remediation_status"]},
        "pass_criteria": {"no_critical_unpatched_over_7d": True, "no_high_unpatched_over_30d": True},
        "integrations": {"sources": ["vulnerability_scanner"]},
        "control_template_codes": ["LM-004"],
    },
    {
        "template_code": "EV-015",
        "title": "Incident Response Plan Document",
        "description": "Current incident response plan document with version and review date.",
        "evidence_type": "document",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "annually",
        "retention_period": "3 years",
        "fields": {"sections": ["plan_version", "review_date", "team_roster", "procedures"]},
        "pass_criteria": {"reviewed_within_12_months": True, "team_roster_current": True},
        "integrations": {},
        "control_template_codes": ["IR-001"],
    },
    {
        "template_code": "EV-016",
        "title": "Tabletop Exercise Report",
        "description": "Report from the most recent incident response tabletop exercise.",
        "evidence_type": "document",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "annually",
        "retention_period": "3 years",
        "fields": {"sections": ["exercise_date", "scenario", "participants", "findings", "action_items"]},
        "pass_criteria": {"exercise_completed": True, "action_items_tracked": True},
        "integrations": {},
        "control_template_codes": ["IR-001", "IR-002"],
    },
    {
        "template_code": "EV-017",
        "title": "EDR Coverage Report",
        "description": "Report showing EDR agent deployment status across all endpoints.",
        "evidence_type": "report",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"columns": ["hostname", "agent_status", "last_check_in", "os_version"]},
        "pass_criteria": {"min_coverage_rate": 98},
        "integrations": {"sources": ["edr_platform"]},
        "control_template_codes": ["ES-001"],
    },
    {
        "template_code": "EV-018",
        "title": "Patch Compliance Report",
        "description": "Report showing patch compliance status across all managed endpoints.",
        "evidence_type": "report",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"columns": ["hostname", "os", "patch_status", "missing_patches", "last_patched"]},
        "pass_criteria": {"min_compliance_rate": 95, "no_critical_missing_over_72h": True},
        "integrations": {"sources": ["patch_management"]},
        "control_template_codes": ["ES-002"],
    },
    {
        "template_code": "EV-019",
        "title": "Background Check Completion Records",
        "description": "Records showing background checks completed for new hires.",
        "evidence_type": "document",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "per_hire",
        "retention_period": "employment + 2 years",
        "fields": {"sections": ["employee_name", "check_date", "check_type", "result", "completed_before_access"]},
        "pass_criteria": {"all_checks_completed": True, "completed_before_access": True},
        "integrations": {"sources": ["hr_system"]},
        "control_template_codes": ["HR-001"],
    },
    {
        "template_code": "EV-020",
        "title": "Security Training Completion Report",
        "description": "Report showing security awareness training completion rates.",
        "evidence_type": "report",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "2 years",
        "fields": {"columns": ["employee_email", "training_module", "completion_date", "score"]},
        "pass_criteria": {"min_completion_rate": 95, "min_passing_score": 80},
        "integrations": {"sources": ["training_platform"]},
        "control_template_codes": ["HR-002"],
    },
]


async def seed_evidence_templates(db):
    from app.models.evidence_template import EvidenceTemplate
    from app.models.control_template import ControlTemplate
    from app.models.control_template_evidence_template import control_template_evidence_templates
    from sqlalchemy import select, insert

    # Check if already seeded
    existing = await db.execute(select(EvidenceTemplate).limit(1))
    if existing.scalar_one_or_none():
        print("Evidence templates already seeded, skipping.")
        return

    for tmpl_data in EVIDENCE_TEMPLATES:
        control_codes = tmpl_data.pop("control_template_codes", [])
        template = EvidenceTemplate(**tmpl_data)
        db.add(template)
        await db.flush()

        for code in control_codes:
            result = await db.execute(
                select(ControlTemplate).where(ControlTemplate.template_code == code)
            )
            ct = result.scalar_one_or_none()
            if ct:
                await db.execute(
                    insert(control_template_evidence_templates).values(
                        control_template_id=ct.id,
                        evidence_template_id=template.id,
                    )
                )

    await db.commit()
    print(f"Seeded {len(EVIDENCE_TEMPLATES)} evidence templates.")
