"""75 extended control templates across 11 security domains."""

EXTENDED_CONTROL_TEMPLATES = [
    # ── Cryptography (5) ──────────────────────────────────────────────
    {
        "template_code": "CRY-001",
        "title": "Cryptographic Key Management",
        "domain": "Cryptography",
        "description": "Establish and maintain a comprehensive cryptographic key management program covering key generation, distribution, storage, rotation, revocation, and destruction.",
        "implementation_guidance": "1. Define key management policy covering full key lifecycle\n2. Use HSM or cloud KMS for key storage and generation\n3. Implement automated key rotation schedules (90 days for symmetric, annual for asymmetric)\n4. Maintain key inventory with ownership and expiration tracking\n5. Define and test key recovery and escrow procedures",
        "test_procedure": "1. Review key management policy and procedures\n2. Verify HSM/KMS usage for key storage\n3. Confirm key rotation schedules are enforced\n4. Audit key inventory for completeness\n5. Test key recovery procedure",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "CRY-002",
        "title": "Encryption at Rest Standards",
        "domain": "Cryptography",
        "description": "Enforce AES-256 or equivalent encryption for all data at rest across databases, file systems, object storage, and backup media.",
        "implementation_guidance": "1. Enable server-side encryption on all cloud storage services\n2. Configure transparent data encryption (TDE) for databases\n3. Encrypt all backup media before storage\n4. Enforce full-disk encryption on endpoints and servers\n5. Verify encryption status through automated configuration scanning",
        "test_procedure": "1. Scan all storage services for encryption configuration\n2. Verify database TDE is enabled\n3. Confirm backup encryption settings\n4. Review endpoint encryption compliance dashboard\n5. Validate encryption algorithm meets minimum standards (AES-256)",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "CRY-003",
        "title": "Encryption in Transit Standards",
        "domain": "Cryptography",
        "description": "Enforce TLS 1.2+ for all data in transit across public and internal networks, including API communications and inter-service traffic.",
        "implementation_guidance": "1. Configure TLS 1.2+ on all public-facing load balancers and endpoints\n2. Enable mutual TLS (mTLS) for service-to-service communication\n3. Disable TLS 1.0, 1.1, SSL 3.0, and weak cipher suites\n4. Implement HSTS headers with a minimum max-age of 1 year\n5. Deploy certificate pinning for critical mobile applications",
        "test_procedure": "1. Run TLS scanner (e.g., SSLLabs, testssl.sh) on all endpoints\n2. Verify minimum TLS 1.2 is enforced\n3. Confirm no weak ciphers are present\n4. Check HSTS header configuration\n5. Test mTLS enforcement for internal services",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "CRY-004",
        "title": "Certificate Lifecycle Management",
        "domain": "Cryptography",
        "description": "Manage the full lifecycle of TLS/SSL certificates including issuance, renewal, revocation, and monitoring for expiration.",
        "implementation_guidance": "1. Deploy a centralized certificate management platform\n2. Automate certificate issuance using ACME protocol (e.g., Let's Encrypt, internal CA)\n3. Configure automated renewal at least 30 days before expiration\n4. Set up alerting for certificates expiring within 60 days\n5. Maintain certificate inventory with owner, purpose, and expiration",
        "test_procedure": "1. Review certificate inventory for completeness\n2. Verify automated renewal is functioning\n3. Check for certificates expiring within 30 days\n4. Confirm alerting is configured and tested\n5. Validate no self-signed certificates in production",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "CRY-005",
        "title": "Cryptographic Standards and Algorithm Policy",
        "domain": "Cryptography",
        "description": "Define and enforce approved cryptographic algorithms, key lengths, and protocols organization-wide.",
        "implementation_guidance": "1. Document approved algorithms: AES-256 (symmetric), RSA-2048+ / ECDSA P-256+ (asymmetric), SHA-256+ (hashing)\n2. Prohibit deprecated algorithms (DES, 3DES, MD5, SHA-1, RC4)\n3. Implement code scanning to detect use of banned cryptographic functions\n4. Review and update cryptographic standards annually\n5. Provide developer guidance on approved cryptographic libraries",
        "test_procedure": "1. Review cryptographic standards policy document\n2. Scan codebase for deprecated algorithm usage\n3. Verify policy is communicated to development teams\n4. Confirm annual review has been performed\n5. Test that banned algorithms are blocked in CI/CD pipeline",
        "automation_level": "semi_automated",
        "variables": {},
    },
    # ── Physical Security (5) ─────────────────────────────────────────
    {
        "template_code": "PHY-001",
        "title": "Facility Access Controls",
        "domain": "Physical Security",
        "description": "Implement physical access controls to restrict entry to facilities housing sensitive systems and data to authorized personnel only.",
        "implementation_guidance": "1. Deploy badge-based or biometric access control systems at all entry points\n2. Implement multi-factor physical authentication for data center access\n3. Maintain access logs with timestamps and identity records\n4. Review facility access lists quarterly and revoke unnecessary access\n5. Implement anti-tailgating measures (mantraps, turnstiles)",
        "test_procedure": "1. Review physical access logs for unauthorized entries\n2. Verify access control system is operational at all entry points\n3. Confirm quarterly access list reviews are performed\n4. Test anti-tailgating mechanisms\n5. Verify terminated employee badges are deactivated within 24 hours",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "PHY-002",
        "title": "Visitor Management",
        "domain": "Physical Security",
        "description": "Establish a visitor management process to track, escort, and control access for non-employees entering secure areas.",
        "implementation_guidance": "1. Implement a visitor registration and sign-in system\n2. Issue temporary visitor badges with expiration dates\n3. Require escort for visitors in restricted areas\n4. Maintain visitor logs with purpose of visit, sponsor, and arrival/departure times\n5. Verify visitor identity with government-issued ID",
        "test_procedure": "1. Review visitor log entries for completeness\n2. Verify visitor badges have expiration dates\n3. Confirm escort policy is followed in restricted areas\n4. Test visitor sign-out process\n5. Verify visitor access to restricted systems is prohibited",
        "automation_level": "manual",
        "variables": {},
    },
    {
        "template_code": "PHY-003",
        "title": "Environmental Controls",
        "domain": "Physical Security",
        "description": "Implement environmental monitoring and protection for facilities housing critical IT infrastructure.",
        "implementation_guidance": "1. Deploy temperature and humidity monitoring in server rooms and data centers\n2. Install fire detection and suppression systems (clean agent or inert gas)\n3. Implement water/leak detection sensors near equipment\n4. Configure environmental alerting thresholds and notifications\n5. Test environmental controls and failover systems semi-annually",
        "test_procedure": "1. Verify environmental monitoring systems are operational\n2. Review alert configurations and thresholds\n3. Confirm fire suppression system inspection is current\n4. Test water detection sensors\n5. Review environmental incident reports from past 12 months",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "PHY-004",
        "title": "Equipment Protection",
        "domain": "Physical Security",
        "description": "Protect IT equipment from theft, tampering, power failures, and environmental damage.",
        "implementation_guidance": "1. Secure servers in locked racks within restricted access areas\n2. Deploy UPS (uninterruptible power supply) and generator backup for critical systems\n3. Implement equipment tagging and inventory management\n4. Install CCTV monitoring of data center and server room areas\n5. Configure tamper detection on critical hardware",
        "test_procedure": "1. Verify server racks are locked and access is controlled\n2. Test UPS failover and generator switchover\n3. Reconcile equipment inventory against physical assets\n4. Review CCTV coverage and recording retention\n5. Confirm tamper detection alerts are functioning",
        "automation_level": "manual",
        "variables": {},
    },
    {
        "template_code": "PHY-005",
        "title": "Secure Media Disposal",
        "domain": "Physical Security",
        "description": "Establish procedures for the secure destruction and disposal of physical media containing sensitive data.",
        "implementation_guidance": "1. Define media disposal procedures for each media type (HDD, SSD, paper, tape)\n2. Use NIST SP 800-88 compliant methods (degaussing, shredding, crypto-erase)\n3. Maintain chain-of-custody records for media pending destruction\n4. Use certified destruction vendors with certificates of destruction\n5. Conduct periodic audits of disposal inventory and processes",
        "test_procedure": "1. Review media disposal policy and procedures\n2. Verify certificates of destruction from disposal vendor\n3. Audit chain-of-custody records for media destruction\n4. Confirm no unwiped media in disposal queue exceeds retention period\n5. Verify destruction methods meet NIST SP 800-88 standards",
        "automation_level": "manual",
        "variables": {},
    },
    # ── Backup & Recovery (5) ─────────────────────────────────────────
    {
        "template_code": "BR-001",
        "title": "Backup Schedule and Automation",
        "domain": "Backup & Recovery",
        "description": "Implement automated backup schedules for all critical systems, databases, and configurations with defined RPO targets.",
        "implementation_guidance": "1. Define backup schedules: daily incremental, weekly full for all production databases\n2. Configure automated backup jobs with monitoring and alerting\n3. Define Recovery Point Objectives (RPO) per system classification\n4. Implement continuous backup / point-in-time recovery for Tier-1 systems\n5. Monitor backup job completion and alert on failures within 1 hour",
        "test_procedure": "1. Review backup schedule configuration for all critical systems\n2. Verify backup job success rates (target: 99%+)\n3. Confirm RPO targets are documented and met\n4. Test backup failure alerting\n5. Validate backup coverage against asset inventory",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "BR-002",
        "title": "Backup Encryption",
        "domain": "Backup & Recovery",
        "description": "Encrypt all backup data at rest and in transit using AES-256 or equivalent encryption standards.",
        "implementation_guidance": "1. Enable encryption on all backup storage destinations\n2. Use customer-managed encryption keys via KMS\n3. Encrypt backup data in transit between source and destination\n4. Ensure backup encryption keys are managed separately from backup data\n5. Document backup encryption key recovery procedures",
        "test_procedure": "1. Verify all backup destinations have encryption enabled\n2. Confirm KMS-managed keys are used for backup encryption\n3. Test that backup data cannot be read without decryption keys\n4. Validate backup key management procedures\n5. Verify backup encryption meets compliance requirements",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "BR-003",
        "title": "Recovery Testing",
        "domain": "Backup & Recovery",
        "description": "Conduct regular backup recovery tests to verify data integrity and restoration capability within RTO targets.",
        "implementation_guidance": "1. Conduct quarterly restoration tests for all Tier-1 systems\n2. Conduct semi-annual restoration tests for Tier-2 systems\n3. Measure and record actual RTO and RPO achieved during tests\n4. Document test results including any issues and corrective actions\n5. Involve application owners in validating restored data integrity",
        "test_procedure": "1. Review restoration test results from the past quarter\n2. Verify RTO targets were met for Tier-1 systems\n3. Confirm data integrity was validated by application owners\n4. Review corrective actions from previous test failures\n5. Verify restoration test coverage matches critical system inventory",
        "automation_level": "manual",
        "variables": {},
    },
    {
        "template_code": "BR-004",
        "title": "Offsite and Cross-Region Backup Storage",
        "domain": "Backup & Recovery",
        "description": "Store backup copies in geographically separate locations or cloud regions to protect against regional disasters.",
        "implementation_guidance": "1. Replicate backups to a secondary cloud region (minimum 200 miles / 300 km separation)\n2. Configure cross-region replication for critical object storage buckets\n3. Verify network connectivity and transfer speeds between regions\n4. Test restoration from the secondary region quarterly\n5. Ensure compliance with data residency requirements for cross-region storage",
        "test_procedure": "1. Verify cross-region replication is configured and active\n2. Confirm geographic separation meets distance requirements\n3. Test restoration from secondary region\n4. Review data residency compliance for backup locations\n5. Validate replication lag meets RPO targets",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "BR-005",
        "title": "Backup Retention Policies",
        "domain": "Backup & Recovery",
        "description": "Define and enforce data backup retention periods aligned with regulatory, legal, and business requirements.",
        "implementation_guidance": "1. Define retention periods: daily backups retained 30 days, weekly 90 days, monthly 1 year, annual 7 years\n2. Implement automated lifecycle policies to expire old backups\n3. Apply legal hold capability for backups subject to litigation or regulatory inquiry\n4. Document retention requirements per data classification level\n5. Audit retention compliance quarterly",
        "test_procedure": "1. Review backup retention policy documentation\n2. Verify automated lifecycle policies are configured\n3. Confirm expired backups are deleted per schedule\n4. Test legal hold functionality\n5. Audit retention compliance against policy",
        "automation_level": "automated",
        "variables": {},
    },
    # ── Cloud Security (10) ───────────────────────────────────────────
    {
        "template_code": "CLD-001",
        "title": "Cloud IAM Policies",
        "domain": "Cloud Security",
        "description": "Implement and enforce least-privilege IAM policies across all cloud accounts and services.",
        "implementation_guidance": "1. Enforce least-privilege principle for all IAM policies\n2. Prohibit use of root/owner accounts for daily operations\n3. Implement IAM Access Analyzer to identify overly permissive policies\n4. Require conditions (MFA, source IP) on sensitive IAM actions\n5. Review and right-size IAM permissions quarterly using access advisor data",
        "test_procedure": "1. Run IAM Access Analyzer and review findings\n2. Verify no wildcard (*) permissions on production resources\n3. Confirm root account has MFA and is not used for daily operations\n4. Review IAM policy changes from the last quarter\n5. Validate service control policies (SCPs) are enforced",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "CLD-002",
        "title": "Cloud Network Segmentation",
        "domain": "Cloud Security",
        "description": "Implement network segmentation in cloud environments to isolate workloads and restrict lateral movement.",
        "implementation_guidance": "1. Segment workloads into separate VPCs/VNets by environment (production, staging, development)\n2. Implement security groups with default-deny inbound rules\n3. Use network ACLs as additional defense layer\n4. Deploy private subnets for databases and internal services\n5. Implement VPC peering or transit gateway with explicit route tables",
        "test_procedure": "1. Review VPC/VNet architecture and segmentation design\n2. Verify security group rules follow least-privilege\n3. Confirm databases are in private subnets with no public IPs\n4. Test network connectivity between segments to verify isolation\n5. Review VPC flow logs for unexpected cross-segment traffic",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "CLD-003",
        "title": "Container Security",
        "domain": "Cloud Security",
        "description": "Secure container images, registries, runtime environments, and orchestration platforms.",
        "implementation_guidance": "1. Scan container images for vulnerabilities before deployment\n2. Use minimal base images and remove unnecessary packages\n3. Enforce image signing and verification in the deployment pipeline\n4. Implement runtime security monitoring for containers\n5. Configure pod security standards (restricted) in Kubernetes",
        "test_procedure": "1. Review container image scanning results from CI/CD pipeline\n2. Verify base images are from approved registries\n3. Confirm image signing is enforced\n4. Test runtime security monitoring alerts\n5. Validate pod security policies are enforced in production clusters",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "CLD-004",
        "title": "Serverless Security",
        "domain": "Cloud Security",
        "description": "Secure serverless functions and event-driven architectures with appropriate IAM permissions, input validation, and monitoring.",
        "implementation_guidance": "1. Apply least-privilege IAM roles to each serverless function\n2. Validate and sanitize all input from event sources\n3. Set function timeout and memory limits to prevent abuse\n4. Enable function-level logging and tracing\n5. Scan function code and dependencies for vulnerabilities",
        "test_procedure": "1. Review IAM roles attached to serverless functions for least privilege\n2. Verify input validation is implemented\n3. Confirm timeout and concurrency limits are configured\n4. Test that function logs are captured in centralized logging\n5. Review dependency scan results for serverless functions",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "CLD-005",
        "title": "Cloud Audit Logging and Monitoring",
        "domain": "Cloud Security",
        "description": "Enable comprehensive audit logging across all cloud services and integrate with centralized SIEM for monitoring and alerting.",
        "implementation_guidance": "1. Enable CloudTrail / Activity Log / Audit Log on all cloud accounts\n2. Configure log delivery to immutable storage (S3 with Object Lock, etc.)\n3. Integrate cloud audit logs with SIEM platform\n4. Create detection rules for high-risk API calls (IAM changes, security group modifications, encryption disabling)\n5. Set log retention to minimum 1 year (active) and 7 years (archive)",
        "test_procedure": "1. Verify audit logging is enabled on all accounts and regions\n2. Confirm log immutability and retention configuration\n3. Test SIEM integration and alerting for high-risk events\n4. Review audit log completeness against cloud service inventory\n5. Validate log retention meets compliance requirements",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "CLD-006",
        "title": "Data Residency and Sovereignty",
        "domain": "Cloud Security",
        "description": "Ensure cloud data storage and processing comply with applicable data residency, sovereignty, and localization requirements.",
        "implementation_guidance": "1. Document data residency requirements by regulation and data classification\n2. Configure cloud services to restrict data to approved regions\n3. Implement service control policies to prevent resource creation in unapproved regions\n4. Maintain a data residency map showing where each data type is stored\n5. Review residency compliance when onboarding new cloud services",
        "test_procedure": "1. Review data residency requirements documentation\n2. Verify cloud resource locations against approved regions\n3. Test service control policies blocking unapproved regions\n4. Audit data residency map for accuracy\n5. Confirm cross-border data transfer mechanisms are documented",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "CLD-007",
        "title": "Shared Responsibility Model Documentation",
        "domain": "Cloud Security",
        "description": "Document and communicate the shared responsibility model between the organization and cloud service providers for each service used.",
        "implementation_guidance": "1. Map security responsibilities for each cloud service (IaaS, PaaS, SaaS)\n2. Document organization's responsibilities vs. CSP responsibilities\n3. Identify gaps in coverage and assign ownership\n4. Train cloud engineering teams on shared responsibility boundaries\n5. Review and update responsibility matrix when adopting new services",
        "test_procedure": "1. Review shared responsibility documentation for completeness\n2. Verify responsibility assignments have named owners\n3. Confirm gap analysis has been performed\n4. Test team awareness of responsibility boundaries\n5. Validate documentation is updated for recently adopted services",
        "automation_level": "manual",
        "variables": {},
    },
    {
        "template_code": "CLD-008",
        "title": "Cloud Key Management",
        "domain": "Cloud Security",
        "description": "Implement cloud-native key management using managed KMS services with customer-managed keys for sensitive workloads.",
        "implementation_guidance": "1. Use cloud KMS for all encryption key management\n2. Create customer-managed keys (CMK) for production workloads\n3. Enable automatic key rotation (annual minimum)\n4. Implement key access policies with least-privilege IAM conditions\n5. Monitor key usage and access patterns through CloudTrail/audit logs",
        "test_procedure": "1. Verify CMKs are used for production workloads instead of default keys\n2. Confirm automatic key rotation is enabled\n3. Review key access policies for least-privilege compliance\n4. Audit key usage logs for unauthorized access attempts\n5. Test key deletion protection (scheduled deletion with wait period)",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "CLD-009",
        "title": "Cloud Workload Protection",
        "domain": "Cloud Security",
        "description": "Deploy cloud workload protection platform (CWPP) to detect threats, vulnerabilities, and misconfigurations across cloud compute workloads.",
        "implementation_guidance": "1. Deploy CWPP agents on all cloud compute instances (EC2, VMs, containers)\n2. Enable file integrity monitoring on critical system files\n3. Configure runtime threat detection and behavioral analysis\n4. Integrate CWPP alerts with SIEM and incident response workflows\n5. Scan workloads for CIS benchmark compliance",
        "test_procedure": "1. Verify CWPP agent coverage across all compute workloads\n2. Review recent threat detections and response actions\n3. Confirm file integrity monitoring is active on critical paths\n4. Test SIEM integration for CWPP alerts\n5. Review CIS benchmark compliance scores",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "CLD-010",
        "title": "Multi-Tenant Isolation",
        "domain": "Cloud Security",
        "description": "Ensure logical and network isolation between tenants in multi-tenant cloud environments and SaaS platforms.",
        "implementation_guidance": "1. Implement tenant isolation at the network, compute, and data layers\n2. Use separate encryption keys per tenant for data-at-rest\n3. Enforce tenant context validation in application authorization logic\n4. Test for cross-tenant data leakage in application and API layers\n5. Document and verify isolation boundaries with architecture diagrams",
        "test_procedure": "1. Review multi-tenant architecture documentation\n2. Test for cross-tenant data access at API and database layers\n3. Verify per-tenant encryption key isolation\n4. Conduct penetration testing targeting tenant isolation boundaries\n5. Review tenant context validation in application code",
        "automation_level": "semi_automated",
        "variables": {},
    },
    # ── Vulnerability Management (10) ─────────────────────────────────
    {
        "template_code": "VM-001",
        "title": "Vulnerability Scanning Program",
        "domain": "Vulnerability Management",
        "description": "Implement a comprehensive vulnerability scanning program covering infrastructure, applications, and cloud configurations.",
        "implementation_guidance": "1. Deploy authenticated vulnerability scanning for all infrastructure assets\n2. Schedule weekly infrastructure scans and daily scans for internet-facing assets\n3. Integrate DAST scanning into CI/CD pipeline for applications\n4. Configure cloud security posture management (CSPM) scanning\n5. Centralize scan results and track remediation in a single dashboard",
        "test_procedure": "1. Verify scanning coverage matches asset inventory\n2. Confirm scan frequency meets policy requirements\n3. Review scan authentication to ensure credentialed scans\n4. Validate CSPM is scanning all cloud accounts\n5. Test that new assets are automatically included in scan scope",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "VM-002",
        "title": "Patch Management Process",
        "domain": "Vulnerability Management",
        "description": "Establish a structured patch management process with defined SLAs for applying security patches based on severity.",
        "implementation_guidance": "1. Define patch SLAs: Critical within 72 hours, High within 14 days, Medium within 30 days, Low within 90 days\n2. Implement automated patch deployment for operating systems\n3. Test patches in staging environment before production deployment\n4. Maintain patch exemption process with risk acceptance documentation\n5. Report patch compliance metrics monthly to security leadership",
        "test_procedure": "1. Review patch compliance report against SLA targets\n2. Verify critical patches were applied within 72-hour window\n3. Confirm staging environment testing for recent patches\n4. Review patch exemptions and risk acceptances\n5. Validate automated patch deployment is functioning",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "VM-003",
        "title": "Penetration Testing Program",
        "domain": "Vulnerability Management",
        "description": "Conduct regular penetration testing of applications, infrastructure, and cloud environments by qualified testers.",
        "implementation_guidance": "1. Conduct annual external penetration test by qualified third party\n2. Conduct semi-annual internal penetration tests\n3. Include web application, API, and cloud infrastructure in scope\n4. Test for OWASP Top 10 and relevant CWE vulnerabilities\n5. Track and remediate findings within defined SLAs (Critical: 30 days, High: 60 days)",
        "test_procedure": "1. Review most recent penetration test report\n2. Verify testing scope covers critical assets\n3. Confirm findings were remediated within SLAs\n4. Validate tester qualifications (OSCP, CREST, etc.)\n5. Review retest results for previously identified findings",
        "automation_level": "manual",
        "variables": {},
    },
    {
        "template_code": "VM-004",
        "title": "Bug Bounty Program",
        "domain": "Vulnerability Management",
        "description": "Operate a bug bounty program to incentivize external security researchers to identify and responsibly disclose vulnerabilities.",
        "implementation_guidance": "1. Establish bug bounty program scope and rules of engagement\n2. Deploy program through a managed platform (e.g., HackerOne, Bugcrowd)\n3. Define reward tiers based on vulnerability severity\n4. Establish triage and response SLAs for submissions\n5. Track and report bug bounty metrics (submissions, valid findings, resolution time)",
        "test_procedure": "1. Review bug bounty program scope and policies\n2. Verify submission triage SLAs are being met\n3. Confirm valid findings are remediated and researchers are rewarded\n4. Review program metrics and trends\n5. Validate program scope covers critical customer-facing assets",
        "automation_level": "manual",
        "variables": {},
    },
    {
        "template_code": "VM-005",
        "title": "Vulnerability Disclosure Policy",
        "domain": "Vulnerability Management",
        "description": "Publish a vulnerability disclosure policy providing clear guidance for external parties to report security vulnerabilities.",
        "implementation_guidance": "1. Publish vulnerability disclosure policy on company website (/.well-known/security.txt)\n2. Provide clear reporting channels (email, web form)\n3. Define response timeline commitments\n4. Include safe harbor language protecting good-faith researchers\n5. Establish internal triage process for incoming disclosures",
        "test_procedure": "1. Verify vulnerability disclosure policy is publicly accessible\n2. Confirm security.txt file is present and current\n3. Test reporting channels are functional\n4. Review response times for recent disclosures\n5. Verify safe harbor language is included",
        "automation_level": "manual",
        "variables": {},
    },
    {
        "template_code": "VM-006",
        "title": "Remediation SLA Enforcement",
        "domain": "Vulnerability Management",
        "description": "Define and enforce vulnerability remediation SLAs with escalation procedures for overdue findings.",
        "implementation_guidance": "1. Define remediation SLAs: Critical 7 days, High 30 days, Medium 60 days, Low 90 days\n2. Implement automated tracking and reporting of SLA compliance\n3. Configure escalation notifications at 50%, 75%, and 100% of SLA window\n4. Require risk acceptance with CISO approval for SLA exceptions\n5. Include SLA compliance in team performance metrics",
        "test_procedure": "1. Review SLA compliance dashboard\n2. Verify escalation notifications are configured and sent\n3. Audit overdue vulnerabilities for risk acceptance documentation\n4. Confirm CISO approval on SLA exceptions\n5. Review SLA compliance trends over past 6 months",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "VM-007",
        "title": "IT Asset Inventory",
        "domain": "Vulnerability Management",
        "description": "Maintain a comprehensive, up-to-date inventory of all IT assets including hardware, software, cloud resources, and services.",
        "implementation_guidance": "1. Deploy automated asset discovery tools covering network, cloud, and endpoint sources\n2. Maintain asset attributes: owner, classification, business criticality, location, OS/version\n3. Reconcile asset inventory weekly against discovery scan results\n4. Integrate asset inventory with vulnerability management and CMDB\n5. Define asset lifecycle states (active, decommissioned, retired)",
        "test_procedure": "1. Review asset inventory completeness against discovery scans\n2. Verify asset attributes are populated and current\n3. Confirm owner assignments for all production assets\n4. Test that new assets are discovered and added within 24 hours\n5. Audit decommissioned assets for removal from active inventory",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "VM-008",
        "title": "Secure Configuration Management",
        "domain": "Vulnerability Management",
        "description": "Establish and enforce secure configuration baselines (CIS Benchmarks) for all system components.",
        "implementation_guidance": "1. Define configuration baselines using CIS Benchmarks for each OS and platform\n2. Implement automated configuration scanning and drift detection\n3. Remediate configuration deviations within defined SLAs\n4. Maintain configuration baseline exceptions with documented risk acceptance\n5. Scan configurations weekly and before production deployment",
        "test_procedure": "1. Review CIS Benchmark compliance scores per platform\n2. Verify automated scanning is configured and running\n3. Confirm drift detection alerts are functioning\n4. Audit configuration exceptions for valid business justification\n5. Test that non-compliant resources are blocked from production deployment",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "VM-009",
        "title": "Software Dependency Scanning",
        "domain": "Vulnerability Management",
        "description": "Scan software dependencies (open-source and third-party libraries) for known vulnerabilities in the development pipeline.",
        "implementation_guidance": "1. Integrate SCA (Software Composition Analysis) tools into CI/CD pipeline\n2. Scan all direct and transitive dependencies on every build\n3. Block builds with critical or high severity dependency vulnerabilities\n4. Maintain a software bill of materials (SBOM) for each application\n5. Monitor for newly disclosed vulnerabilities in existing dependencies",
        "test_procedure": "1. Verify SCA scanning is integrated into all build pipelines\n2. Test that builds with critical vulnerabilities are blocked\n3. Review SBOM completeness for production applications\n4. Confirm continuous monitoring for new CVEs in deployed dependencies\n5. Audit dependency update frequency and remediation times",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "VM-010",
        "title": "Security Advisory Monitoring",
        "domain": "Vulnerability Management",
        "description": "Monitor security advisories from vendors, CERTs, and threat intelligence sources to proactively identify relevant vulnerabilities.",
        "implementation_guidance": "1. Subscribe to security advisories from all major software and cloud vendors\n2. Monitor CISA, US-CERT, and relevant industry ISACs for threat advisories\n3. Establish triage process to assess advisory applicability to the environment\n4. Define emergency patching process for zero-day vulnerabilities\n5. Communicate relevant advisories to affected system owners within 4 hours",
        "test_procedure": "1. Verify advisory monitoring subscriptions are active\n2. Review advisory triage log from the past month\n3. Test emergency patching process with a tabletop scenario\n4. Confirm communication timelines are met for recent advisories\n5. Validate applicability assessments are documented",
        "automation_level": "semi_automated",
        "variables": {},
    },
    # ── Vendor Management (5) ─────────────────────────────────────────
    {
        "template_code": "VND-001",
        "title": "Vendor Security Assessment",
        "domain": "Vendor Management",
        "description": "Conduct security assessments of all vendors and third parties that access, process, or store organizational data.",
        "implementation_guidance": "1. Develop a vendor security assessment questionnaire based on SIG/CAIQ standards\n2. Classify vendors by risk tier (critical, high, medium, low) based on data access\n3. Require SOC 2 Type II or ISO 27001 certification for critical vendors\n4. Conduct due diligence assessments before onboarding new vendors\n5. Re-assess critical vendors annually and others biannually",
        "test_procedure": "1. Review vendor risk classification inventory\n2. Verify security assessments are completed for all critical vendors\n3. Confirm assessment questionnaires cover required security domains\n4. Audit vendor certifications (SOC 2, ISO 27001) for current validity\n5. Review remediation tracking for vendor assessment findings",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "VND-002",
        "title": "Vendor SLA Management",
        "domain": "Vendor Management",
        "description": "Define and monitor security-related SLAs in vendor contracts including uptime, incident notification, and data protection requirements.",
        "implementation_guidance": "1. Include security SLAs in all vendor contracts (incident notification within 24 hours, uptime 99.9%)\n2. Require vendors to notify of breaches, material changes, and sub-processor additions\n3. Define audit rights and evidence provision requirements\n4. Monitor vendor SLA compliance through regular reporting\n5. Establish consequences for SLA breaches including contract termination rights",
        "test_procedure": "1. Review vendor contracts for security SLA clauses\n2. Verify vendor SLA compliance reports are received\n3. Confirm incident notification requirements are documented\n4. Audit vendor breach notifications from the past year\n5. Review SLA breach escalation records",
        "automation_level": "manual",
        "variables": {},
    },
    {
        "template_code": "VND-003",
        "title": "Vendor Data Handling Requirements",
        "domain": "Vendor Management",
        "description": "Define and enforce requirements for how vendors handle, store, transmit, and dispose of organizational data.",
        "implementation_guidance": "1. Include data handling requirements in data processing agreements (DPAs)\n2. Require encryption of organizational data at rest and in transit\n3. Restrict vendor data access to minimum necessary for service delivery\n4. Require secure data disposal upon contract termination with certification\n5. Prohibit vendor use of organizational data for secondary purposes",
        "test_procedure": "1. Review DPAs for completeness of data handling requirements\n2. Verify encryption requirements are contractually specified\n3. Confirm data access limitations are documented\n4. Review data disposal certifications from terminated vendor relationships\n5. Audit vendor data handling practices through questionnaire or site visit",
        "automation_level": "manual",
        "variables": {},
    },
    {
        "template_code": "VND-004",
        "title": "Third-Party Access Management",
        "domain": "Vendor Management",
        "description": "Control and monitor access granted to third-party vendors to organizational systems and data.",
        "implementation_guidance": "1. Grant vendor access using dedicated vendor accounts with unique identifiers\n2. Enforce MFA for all vendor remote access\n3. Implement time-limited access with automatic expiration\n4. Log and monitor all vendor access activities\n5. Review and recertify vendor access quarterly",
        "test_procedure": "1. Audit vendor accounts for compliance with naming and identification standards\n2. Verify MFA is enforced on all vendor accounts\n3. Confirm time-limited access configurations are in place\n4. Review vendor access logs for anomalous activities\n5. Verify quarterly access recertification is completed",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "VND-005",
        "title": "Vendor Offboarding",
        "domain": "Vendor Management",
        "description": "Implement a structured vendor offboarding process to revoke access, retrieve data, and obtain destruction certifications upon contract termination.",
        "implementation_guidance": "1. Define vendor offboarding checklist covering access, data, and contractual obligations\n2. Revoke all vendor system access within 24 hours of contract termination\n3. Request return or certified destruction of all organizational data\n4. Verify removal of vendor integrations and API connections\n5. Conduct final review and document offboarding completion",
        "test_procedure": "1. Review vendor offboarding checklist for completeness\n2. Verify access revocation for recently terminated vendors\n3. Confirm data destruction certifications are on file\n4. Audit API connections and integrations for terminated vendors\n5. Review offboarding completion documentation",
        "automation_level": "manual",
        "variables": {},
    },
    # ── Business Continuity (5) ───────────────────────────────────────
    {
        "template_code": "BC-001",
        "title": "Business Continuity Plan",
        "domain": "Business Continuity",
        "description": "Develop and maintain a comprehensive business continuity plan (BCP) to ensure critical business functions continue during and after a disruption.",
        "implementation_guidance": "1. Identify critical business processes and their dependencies\n2. Define continuity strategies for each critical process\n3. Document manual workarounds for technology-dependent processes\n4. Assign BCP roles and responsibilities with alternates\n5. Review and update BCP annually and after significant organizational changes",
        "test_procedure": "1. Review BCP document for completeness and currency\n2. Verify critical business processes are identified and prioritized\n3. Confirm continuity strategies are documented for each critical process\n4. Validate BCP roles have current contact information\n5. Review BCP update history for annual reviews",
        "automation_level": "manual",
        "variables": {},
    },
    {
        "template_code": "BC-002",
        "title": "Disaster Recovery Plan and Testing",
        "domain": "Business Continuity",
        "description": "Implement and regularly test a disaster recovery plan covering IT infrastructure, applications, and data recovery.",
        "implementation_guidance": "1. Document disaster recovery procedures for all critical systems\n2. Define RTO and RPO targets for each system tier\n3. Implement automated failover for Tier-1 systems\n4. Conduct annual full-scale DR test and semi-annual tabletop exercises\n5. Document test results and remediate gaps within 30 days",
        "test_procedure": "1. Review DR plan documentation for completeness\n2. Verify RTO/RPO targets are defined for all critical systems\n3. Review most recent DR test results and gap remediation\n4. Confirm automated failover is configured for Tier-1 systems\n5. Validate DR test frequency meets policy requirements",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "BC-003",
        "title": "Crisis Communication Plan",
        "domain": "Business Continuity",
        "description": "Establish a crisis communication plan defining how the organization communicates with stakeholders during and after an incident or disaster.",
        "implementation_guidance": "1. Define communication roles: spokesperson, internal comms lead, customer liaison\n2. Pre-draft communication templates for common scenarios (outage, breach, disaster)\n3. Establish communication channels (status page, email, social media, SMS)\n4. Define escalation thresholds for executive and board notification\n5. Conduct crisis communication exercises annually",
        "test_procedure": "1. Review crisis communication plan for completeness\n2. Verify communication templates are pre-drafted and approved\n3. Confirm communication channels are operational and tested\n4. Review escalation threshold definitions\n5. Validate annual exercise was conducted with lessons learned documented",
        "automation_level": "manual",
        "variables": {},
    },
    {
        "template_code": "BC-004",
        "title": "Business Impact Analysis",
        "domain": "Business Continuity",
        "description": "Conduct business impact analysis (BIA) to identify critical processes, assess disruption impacts, and define recovery priorities.",
        "implementation_guidance": "1. Identify all business processes and their owners\n2. Assess financial, operational, regulatory, and reputational impacts of disruption\n3. Determine Maximum Tolerable Downtime (MTD) for each process\n4. Map technology dependencies for each critical process\n5. Review and update BIA annually or after significant business changes",
        "test_procedure": "1. Review BIA documentation for completeness\n2. Verify all critical processes have assigned owners and MTD values\n3. Confirm impact assessments cover financial, operational, regulatory, and reputational dimensions\n4. Validate technology dependency mapping is current\n5. Review BIA update history for annual reviews",
        "automation_level": "manual",
        "variables": {},
    },
    {
        "template_code": "BC-005",
        "title": "Recovery Time and Point Objectives",
        "domain": "Business Continuity",
        "description": "Define, document, and validate Recovery Time Objectives (RTO) and Recovery Point Objectives (RPO) for all critical systems.",
        "implementation_guidance": "1. Define RTO/RPO for each system based on BIA results and business requirements\n2. Tier systems: Tier-1 (RTO < 1 hr, RPO < 15 min), Tier-2 (RTO < 4 hr, RPO < 1 hr), Tier-3 (RTO < 24 hr, RPO < 24 hr)\n3. Align backup, replication, and failover configurations with RTO/RPO targets\n4. Validate RTO/RPO achievement through DR testing\n5. Report RTO/RPO compliance to business stakeholders quarterly",
        "test_procedure": "1. Review RTO/RPO definitions for all critical systems\n2. Verify backup and replication configurations align with targets\n3. Review DR test results for actual RTO/RPO achievement\n4. Confirm business stakeholder sign-off on RTO/RPO targets\n5. Validate tiering assignments match BIA priorities",
        "automation_level": "semi_automated",
        "variables": {},
    },
    # ── Privacy (5) ───────────────────────────────────────────────────
    {
        "template_code": "PRV-001",
        "title": "Consent Management",
        "domain": "Privacy",
        "description": "Implement a consent management system to collect, record, and manage user consent for data processing activities.",
        "implementation_guidance": "1. Deploy a consent management platform (CMP) for web and mobile applications\n2. Present clear, granular consent options for each processing purpose\n3. Record consent with timestamp, version, and scope\n4. Enable users to withdraw consent at any time with equal ease\n5. Propagate consent changes to downstream systems and processors",
        "test_procedure": "1. Review CMP configuration and consent options\n2. Verify consent records include required metadata (timestamp, version, scope)\n3. Test consent withdrawal flow end-to-end\n4. Confirm consent changes propagate to downstream systems\n5. Audit consent banner compliance with regulatory requirements",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "PRV-002",
        "title": "Data Subject Request Handling",
        "domain": "Privacy",
        "description": "Implement processes to receive, verify, and fulfill data subject requests (access, deletion, portability, rectification) within regulatory timeframes.",
        "implementation_guidance": "1. Establish intake channels for DSR submissions (web form, email, in-app)\n2. Implement identity verification process before fulfilling requests\n3. Define workflows for each request type (access, deletion, portability, rectification)\n4. Track request status and ensure fulfillment within 30 days (GDPR) or applicable timeframe\n5. Maintain request logs with timestamps, actions taken, and completion dates",
        "test_procedure": "1. Review DSR intake channels for accessibility and functionality\n2. Verify identity verification process is documented and followed\n3. Audit recent DSR fulfillment for timeline compliance\n4. Test end-to-end DSR workflow for each request type\n5. Review DSR log completeness and accuracy",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "PRV-003",
        "title": "Privacy Impact Assessment",
        "domain": "Privacy",
        "description": "Conduct privacy impact assessments (PIAs) for new processing activities, systems, and significant changes to existing processing.",
        "implementation_guidance": "1. Define criteria for when a PIA is required (new processing, new vendor, significant change)\n2. Create standardized PIA template covering data flows, legal basis, risks, and mitigations\n3. Require DPO review and approval of all PIAs\n4. Track PIA findings and remediation actions\n5. Integrate PIA requirements into project management and change management processes",
        "test_procedure": "1. Review PIA policy and triggering criteria\n2. Verify PIAs were conducted for recent new processing activities\n3. Confirm DPO review and approval on completed PIAs\n4. Audit PIA finding remediation status\n5. Validate PIA integration with project intake process",
        "automation_level": "manual",
        "variables": {},
    },
    {
        "template_code": "PRV-004",
        "title": "Data Retention and Disposal",
        "domain": "Privacy",
        "description": "Define and enforce data retention schedules to ensure personal data is retained only as long as necessary and securely disposed when no longer needed.",
        "implementation_guidance": "1. Define retention periods for each data category based on legal, regulatory, and business requirements\n2. Implement automated data lifecycle policies to flag and delete expired data\n3. Apply legal hold capabilities for data subject to litigation or regulatory inquiry\n4. Maintain a data retention schedule document with owner sign-off\n5. Audit retention compliance quarterly",
        "test_procedure": "1. Review data retention schedule for completeness\n2. Verify automated lifecycle policies are configured and active\n3. Confirm expired data is deleted per schedule\n4. Test legal hold functionality\n5. Audit data stores for retention compliance",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "PRV-005",
        "title": "Cross-Border Data Transfers",
        "domain": "Privacy",
        "description": "Implement appropriate safeguards for transferring personal data across international borders in compliance with applicable regulations.",
        "implementation_guidance": "1. Map all cross-border data transfers including transfer mechanisms and destinations\n2. Implement appropriate transfer mechanisms (SCCs, BCRs, adequacy decisions)\n3. Conduct Transfer Impact Assessments (TIAs) for transfers to non-adequate jurisdictions\n4. Monitor regulatory changes affecting transfer mechanisms\n5. Maintain documentation of transfer safeguards for each data flow",
        "test_procedure": "1. Review cross-border data transfer inventory\n2. Verify appropriate transfer mechanisms are in place for each flow\n3. Confirm TIAs are completed for non-adequate jurisdictions\n4. Audit SCCs/BCRs for current validity\n5. Review monitoring process for regulatory changes",
        "automation_level": "manual",
        "variables": {},
    },
    # ── Identity & Access Management (10) ─────────────────────────────
    {
        "template_code": "IAM-001",
        "title": "MFA Enforcement",
        "domain": "Identity & Access Management",
        "description": "Enforce multi-factor authentication across all user accounts, with phishing-resistant methods required for privileged access.",
        "implementation_guidance": "1. Require MFA for all user accounts accessing corporate systems\n2. Enforce phishing-resistant MFA (FIDO2/WebAuthn) for privileged accounts\n3. Implement conditional access policies requiring MFA for risky sign-ins\n4. Disable SMS-based MFA in favor of authenticator apps or hardware keys\n5. Monitor MFA enrollment rates and follow up on non-compliant users",
        "test_procedure": "1. Review MFA enrollment rates (target: 100%)\n2. Verify phishing-resistant MFA for privileged accounts\n3. Test conditional access policies trigger MFA appropriately\n4. Confirm SMS-based MFA is disabled or deprecated\n5. Audit MFA bypass or fallback mechanisms",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "IAM-002",
        "title": "SSO Integration",
        "domain": "Identity & Access Management",
        "description": "Integrate all business applications with centralized SSO to enforce consistent authentication and access policies.",
        "implementation_guidance": "1. Integrate all SaaS applications with corporate SSO (SAML 2.0 / OIDC)\n2. Disable local authentication on SSO-integrated applications\n3. Maintain inventory of SSO-integrated vs. non-integrated applications\n4. Set session duration and re-authentication policies\n5. Prioritize SSO integration for applications handling sensitive data",
        "test_procedure": "1. Review SSO integration inventory for completeness\n2. Verify local authentication is disabled on integrated applications\n3. Test session timeout and re-authentication enforcement\n4. Confirm new application onboarding includes SSO integration requirement\n5. Audit non-integrated applications for risk acceptance",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "IAM-003",
        "title": "Privileged Access Management (PAM)",
        "domain": "Identity & Access Management",
        "description": "Implement a privileged access management solution to control, monitor, and audit elevated access to critical systems.",
        "implementation_guidance": "1. Deploy PAM solution for all privileged account access\n2. Implement just-in-time (JIT) access elevation with time-limited grants\n3. Record all privileged sessions for audit and forensic purposes\n4. Implement approval workflows for privileged access requests\n5. Rotate privileged credentials automatically after each use or on schedule",
        "test_procedure": "1. Verify PAM solution is deployed and covers all privileged accounts\n2. Test JIT access elevation workflow\n3. Review session recordings from the past month\n4. Confirm approval workflows are enforced for elevated access\n5. Validate automated credential rotation is functioning",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "IAM-004",
        "title": "Role-Based Access Control",
        "domain": "Identity & Access Management",
        "description": "Implement role-based access control (RBAC) with well-defined roles mapped to job functions and business needs.",
        "implementation_guidance": "1. Define access roles based on job functions and departments\n2. Create role-permission matrices documenting access for each role\n3. Implement RBAC in identity provider, cloud IAM, and applications\n4. Prohibit direct user-level permission grants; use roles exclusively\n5. Review and update role definitions quarterly",
        "test_procedure": "1. Review role-permission matrix for completeness\n2. Verify no direct user-level permissions exist (roles only)\n3. Confirm role assignments align with current job functions\n4. Audit role definitions for excessive permissions\n5. Validate quarterly role review was conducted",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "IAM-005",
        "title": "Automated Access Provisioning",
        "domain": "Identity & Access Management",
        "description": "Automate user access provisioning through HR system integration to ensure timely and accurate access grants on hire and role change.",
        "implementation_guidance": "1. Integrate HRIS with identity provider for automated account creation\n2. Map HR job codes to access roles for automated provisioning\n3. Trigger access modifications on role/department changes\n4. Implement approval workflows for access beyond standard role grants\n5. Log all provisioning events for audit purposes",
        "test_procedure": "1. Review HRIS-to-IDP integration for active synchronization\n2. Test automated provisioning for a new hire scenario\n3. Verify role change triggers access modification\n4. Audit provisioning logs for completeness\n5. Confirm approval workflows for non-standard access requests",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "IAM-006",
        "title": "Automated Access Deprovisioning",
        "domain": "Identity & Access Management",
        "description": "Automate user access deprovisioning on termination to revoke all system access within defined timeframes.",
        "implementation_guidance": "1. Integrate HRIS termination events with identity provider for automated deprovisioning\n2. Revoke all access within 4 hours of termination for standard separations\n3. Implement immediate revocation capability for involuntary terminations\n4. Revoke access across all SSO-integrated and non-integrated applications\n5. Verify access revocation completeness through automated reporting",
        "test_procedure": "1. Review recent terminations and verify access revocation timing\n2. Test automated deprovisioning workflow end-to-end\n3. Verify no orphaned accounts exist for terminated employees\n4. Confirm immediate revocation capability is functional\n5. Audit non-SSO applications for manual deprovisioning compliance",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "IAM-007",
        "title": "Service Account Management",
        "domain": "Identity & Access Management",
        "description": "Manage service accounts with proper governance including ownership, credential rotation, and least-privilege access.",
        "implementation_guidance": "1. Maintain inventory of all service accounts with designated owners\n2. Apply least-privilege permissions to each service account\n3. Rotate service account credentials on a defined schedule (90 days minimum)\n4. Disable interactive login for service accounts\n5. Monitor service account usage for anomalous activity",
        "test_procedure": "1. Review service account inventory for completeness and ownership\n2. Verify service account permissions follow least privilege\n3. Confirm credential rotation is occurring per schedule\n4. Test that interactive login is disabled for service accounts\n5. Review service account activity monitoring alerts",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "IAM-008",
        "title": "API Key and Token Management",
        "domain": "Identity & Access Management",
        "description": "Manage API keys and tokens with proper lifecycle controls including generation, rotation, scoping, and revocation.",
        "implementation_guidance": "1. Generate API keys with minimum required permissions (scoped access)\n2. Implement automatic API key expiration and rotation (90 days maximum)\n3. Store API keys in secrets management systems (never in source code)\n4. Monitor API key usage for anomalous patterns\n5. Implement automated scanning to detect API keys in code repositories",
        "test_procedure": "1. Audit API key inventory for proper scoping and ownership\n2. Verify automatic expiration and rotation are configured\n3. Scan repositories for embedded API keys or secrets\n4. Review API key usage monitoring dashboards\n5. Test API key revocation process",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "IAM-009",
        "title": "Session Management",
        "domain": "Identity & Access Management",
        "description": "Implement secure session management controls including timeouts, concurrent session limits, and session invalidation.",
        "implementation_guidance": "1. Set idle session timeout to 15 minutes for sensitive applications\n2. Set absolute session timeout to 8 hours for standard applications\n3. Implement concurrent session detection and limiting\n4. Invalidate sessions on password change and account modification\n5. Implement secure session token generation and transmission (HttpOnly, Secure flags)",
        "test_procedure": "1. Verify session timeout configurations across applications\n2. Test idle timeout enforcement\n3. Confirm session invalidation on password change\n4. Verify session tokens use secure flags (HttpOnly, Secure, SameSite)\n5. Test concurrent session limiting behavior",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "IAM-010",
        "title": "Directory Services and Identity Governance",
        "domain": "Identity & Access Management",
        "description": "Maintain centralized directory services as the authoritative source for identity, authentication, and group membership.",
        "implementation_guidance": "1. Designate corporate directory (e.g., Azure AD, Okta) as authoritative identity source\n2. Synchronize directory with HRIS for employee lifecycle management\n3. Implement group-based access management with nested group support\n4. Enforce naming conventions for groups, service accounts, and distribution lists\n5. Audit directory for stale accounts, orphaned groups, and inconsistencies monthly",
        "test_procedure": "1. Verify directory is synchronized with HRIS\n2. Confirm group-based access management is implemented\n3. Audit directory for stale accounts (no login in 90+ days)\n4. Review orphaned groups and unused distribution lists\n5. Validate naming conventions are enforced",
        "automation_level": "semi_automated",
        "variables": {},
    },
    # ── Security Awareness (5) ────────────────────────────────────────
    {
        "template_code": "SAT-001",
        "title": "Phishing Simulation Training",
        "domain": "Security Awareness",
        "description": "Conduct regular phishing simulations to assess and improve employee resilience to social engineering attacks.",
        "implementation_guidance": "1. Conduct phishing simulations monthly with varying difficulty levels\n2. Include diverse attack vectors: email, SMS, voice (vishing)\n3. Provide immediate training feedback to users who fall for simulations\n4. Require remedial training for repeat offenders (3+ failures)\n5. Track and report phishing resilience metrics to leadership",
        "test_procedure": "1. Review phishing simulation results from the past quarter\n2. Verify simulation frequency meets monthly target\n3. Confirm immediate feedback is provided to affected users\n4. Review remedial training completion for repeat offenders\n5. Validate phishing resilience trend is improving",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "SAT-002",
        "title": "Security Onboarding Training",
        "domain": "Security Awareness",
        "description": "Require all new employees to complete security awareness training within the first 30 days of employment.",
        "implementation_guidance": "1. Develop comprehensive security onboarding module covering data handling, password hygiene, phishing awareness, and incident reporting\n2. Integrate training assignment into HR onboarding workflow\n3. Require training completion within 30 days of hire date\n4. Require passing score of 80% or higher on assessment\n5. Block production system access until training is completed",
        "test_procedure": "1. Verify all recent hires completed training within 30 days\n2. Review assessment pass rates and scores\n3. Confirm training content is current and relevant\n4. Test that access is restricted until training completion\n5. Audit training content review history",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "SAT-003",
        "title": "Security Incident Reporting Procedures",
        "domain": "Security Awareness",
        "description": "Train employees on security incident reporting procedures and provide accessible reporting channels.",
        "implementation_guidance": "1. Publish clear incident reporting procedures on company intranet\n2. Provide multiple reporting channels (email, Slack, phone, web form)\n3. Deploy phishing report button in email client\n4. Include incident reporting in annual security awareness training\n5. Recognize and reward employees who report genuine security concerns",
        "test_procedure": "1. Verify incident reporting procedures are published and accessible\n2. Test all reporting channels for functionality\n3. Confirm phishing report button is deployed on all email clients\n4. Review incident reporting metrics (volume, quality, response time)\n5. Validate employee recognition program for security reporters",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "SAT-004",
        "title": "Social Engineering Awareness",
        "domain": "Security Awareness",
        "description": "Provide targeted training on social engineering tactics including pretexting, baiting, tailgating, and business email compromise.",
        "implementation_guidance": "1. Develop training modules for each social engineering vector\n2. Include real-world case studies and examples from recent incidents\n3. Conduct tabletop exercises for high-risk departments (finance, HR, executives)\n4. Provide role-specific training for executives on BEC and whaling attacks\n5. Update content quarterly to reflect emerging social engineering techniques",
        "test_procedure": "1. Review social engineering training module content\n2. Verify training completion rates by department\n3. Confirm executive-specific training is provided\n4. Test employee awareness through social engineering assessments\n5. Validate training content is updated with recent examples",
        "automation_level": "manual",
        "variables": {},
    },
    {
        "template_code": "SAT-005",
        "title": "Security Champions Program",
        "domain": "Security Awareness",
        "description": "Establish a security champions program embedding security-focused advocates within engineering and business teams.",
        "implementation_guidance": "1. Recruit security champions from each engineering and business team\n2. Provide advanced security training and resources to champions\n3. Define champion responsibilities: code review, security guidance, incident coordination\n4. Hold monthly security champion meetings and knowledge-sharing sessions\n5. Recognize and reward champion contributions through performance reviews",
        "test_procedure": "1. Verify security champion roster covers all teams\n2. Review champion training completion and certifications\n3. Confirm monthly champion meetings are occurring\n4. Review champion contributions (code reviews, guidance sessions)\n5. Validate champion program metrics and impact assessment",
        "automation_level": "manual",
        "variables": {},
    },
    # ── Application Security (10) ─────────────────────────────────────
    {
        "template_code": "APP-001",
        "title": "Static and Dynamic Application Security Testing (SAST/DAST)",
        "domain": "Application Security",
        "description": "Implement automated SAST and DAST scanning in the development pipeline to identify application security vulnerabilities.",
        "implementation_guidance": "1. Integrate SAST tools into CI/CD pipeline to scan on every commit\n2. Configure DAST scanning against staging environments before release\n3. Define quality gates that block deployment for critical and high findings\n4. Triage findings with development teams within 5 business days\n5. Track false positive rates and tune scanner rules to reduce noise",
        "test_procedure": "1. Verify SAST is integrated into all CI/CD pipelines\n2. Confirm DAST scans are running against staging before releases\n3. Test that quality gates block deployment for critical findings\n4. Review finding triage and remediation metrics\n5. Audit false positive rate and tuning effectiveness",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "APP-002",
        "title": "Mandatory Code Review",
        "domain": "Application Security",
        "description": "Require peer code review for all production code changes with security-focused review criteria.",
        "implementation_guidance": "1. Enforce branch protection requiring at least one approving review\n2. Require security-focused review for changes touching authentication, authorization, cryptography, and data handling\n3. Assign security champions as reviewers for high-risk changes\n4. Provide code review checklists covering OWASP Top 10 concerns\n5. Prohibit self-approval and require re-review after force push",
        "test_procedure": "1. Verify branch protection rules are enforced on production branches\n2. Audit recent merges for review approval compliance\n3. Confirm security champion review for high-risk changes\n4. Review code review checklist usage\n5. Validate no self-approvals occurred in the review period",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "APP-003",
        "title": "Secure Software Development Lifecycle (SSDLC)",
        "domain": "Application Security",
        "description": "Integrate security activities throughout the software development lifecycle from design through deployment and maintenance.",
        "implementation_guidance": "1. Define secure SDLC phases: requirements, design, development, testing, deployment, maintenance\n2. Conduct threat modeling during design phase for new features and services\n3. Integrate security testing (SAST, DAST, SCA) into development and CI/CD\n4. Require security sign-off before production deployment\n5. Conduct post-deployment security verification within 7 days",
        "test_procedure": "1. Review SSDLC policy and process documentation\n2. Verify threat modeling was conducted for recent new features\n3. Confirm security testing is integrated at each phase\n4. Audit security sign-off records for recent deployments\n5. Review post-deployment security verification results",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "APP-004",
        "title": "API Security",
        "domain": "Application Security",
        "description": "Implement security controls for APIs including authentication, authorization, rate limiting, input validation, and monitoring.",
        "implementation_guidance": "1. Require OAuth 2.0 / OpenID Connect for API authentication\n2. Implement API-level authorization with scope-based access control\n3. Configure rate limiting and throttling to prevent abuse\n4. Validate all API inputs and reject unexpected parameters\n5. Log all API requests for monitoring and anomaly detection",
        "test_procedure": "1. Verify OAuth/OIDC is enforced on all API endpoints\n2. Test API authorization for proper scope enforcement\n3. Validate rate limiting configuration and behavior\n4. Test input validation with malformed and oversized payloads\n5. Review API access logs for completeness and anomaly detection",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "APP-005",
        "title": "Input Validation Controls",
        "domain": "Application Security",
        "description": "Implement comprehensive input validation on all user-supplied data to prevent injection attacks and data corruption.",
        "implementation_guidance": "1. Validate all inputs on the server side (never trust client-side validation alone)\n2. Use parameterized queries or ORM for all database interactions\n3. Implement allowlist validation for expected input formats\n4. Reject inputs exceeding maximum length, type, or pattern constraints\n5. Sanitize inputs used in dynamic content generation",
        "test_procedure": "1. Review code for parameterized query usage (no string concatenation in SQL)\n2. Test for SQL injection, NoSQL injection, and command injection\n3. Verify server-side validation is implemented for all input endpoints\n4. Test boundary conditions with oversized and malformed inputs\n5. Validate input sanitization for dynamic content",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "APP-006",
        "title": "Output Encoding",
        "domain": "Application Security",
        "description": "Implement context-appropriate output encoding to prevent cross-site scripting (XSS) and injection attacks.",
        "implementation_guidance": "1. Apply HTML entity encoding for all untrusted data in HTML context\n2. Use JavaScript encoding for data inserted into JavaScript blocks\n3. Apply URL encoding for untrusted data in URL parameters\n4. Implement Content Security Policy (CSP) headers to mitigate XSS\n5. Use templating engines with auto-escaping enabled by default",
        "test_procedure": "1. Verify templating engines have auto-escaping enabled\n2. Test for reflected and stored XSS vulnerabilities\n3. Review Content Security Policy header configuration\n4. Confirm output encoding is applied in all rendering contexts\n5. Validate CSP violation reporting is configured",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "APP-007",
        "title": "Application Authentication Controls",
        "domain": "Application Security",
        "description": "Implement robust authentication controls in applications including secure credential storage, brute-force protection, and secure password reset.",
        "implementation_guidance": "1. Store passwords using strong hashing (bcrypt, scrypt, or Argon2 with appropriate cost factors)\n2. Implement account lockout after 5 consecutive failed attempts with progressive delays\n3. Enforce secure password reset flow with time-limited tokens\n4. Implement CAPTCHA or rate limiting on authentication endpoints\n5. Log authentication events for monitoring and anomaly detection",
        "test_procedure": "1. Verify password hashing algorithm and cost factor configuration\n2. Test account lockout behavior after failed attempts\n3. Validate password reset flow security (token expiration, single use)\n4. Test brute-force protection mechanisms\n5. Review authentication event logs for completeness",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "APP-008",
        "title": "Application Authorization Controls",
        "domain": "Application Security",
        "description": "Implement proper authorization checks in applications to prevent unauthorized access to data and functionality.",
        "implementation_guidance": "1. Implement server-side authorization checks for every API endpoint and action\n2. Enforce object-level authorization (BOLA/IDOR prevention)\n3. Implement function-level authorization for privileged operations\n4. Use deny-by-default authorization policy\n5. Log authorization failures for monitoring and alerting",
        "test_procedure": "1. Test for horizontal privilege escalation (BOLA/IDOR) across endpoints\n2. Test for vertical privilege escalation (accessing admin functions as regular user)\n3. Verify server-side authorization on all API endpoints\n4. Confirm deny-by-default policy is implemented\n5. Review authorization failure logs for suspicious patterns",
        "automation_level": "semi_automated",
        "variables": {},
    },
    {
        "template_code": "APP-009",
        "title": "Error Handling and Information Leakage Prevention",
        "domain": "Application Security",
        "description": "Implement secure error handling to prevent information leakage through error messages, stack traces, and debug information.",
        "implementation_guidance": "1. Return generic error messages to users (no stack traces, SQL errors, or internal details)\n2. Log detailed error information server-side for debugging\n3. Disable debug mode and verbose error reporting in production\n4. Implement custom error pages for common HTTP error codes\n5. Remove server version headers and technology fingerprints from responses",
        "test_procedure": "1. Test error responses for information leakage (stack traces, SQL details)\n2. Verify debug mode is disabled in production\n3. Confirm custom error pages are configured\n4. Check response headers for server version disclosure\n5. Test exception handling for unhandled edge cases",
        "automation_level": "automated",
        "variables": {},
    },
    {
        "template_code": "APP-010",
        "title": "Security Headers Configuration",
        "domain": "Application Security",
        "description": "Configure HTTP security headers to protect against common web application attacks.",
        "implementation_guidance": "1. Implement Content-Security-Policy (CSP) with restrictive directives\n2. Enable Strict-Transport-Security (HSTS) with minimum 1-year max-age and includeSubDomains\n3. Set X-Content-Type-Options: nosniff\n4. Configure X-Frame-Options: DENY or SAMEORIGIN\n5. Implement Permissions-Policy to restrict browser features\n6. Set Referrer-Policy: strict-origin-when-cross-origin",
        "test_procedure": "1. Scan all endpoints for security header presence using automated tools\n2. Validate CSP directive restrictiveness\n3. Verify HSTS configuration including preload eligibility\n4. Confirm X-Frame-Options and X-Content-Type-Options are set\n5. Review Permissions-Policy for appropriate browser feature restrictions",
        "automation_level": "automated",
        "variables": {},
    },
]


async def seed_extended_control_templates(db):
    """Seed 75 extended control templates across 11 security domains."""
    from app.models.control_template import ControlTemplate
    from sqlalchemy import select

    # Check if any of these templates already exist
    existing = await db.execute(
        select(ControlTemplate).where(ControlTemplate.template_code == "CRY-001")
    )
    if existing.scalar_one_or_none():
        print("  -> Extended control templates already seeded, skipping.")
        return

    count = 0
    for tmpl_data in EXTENDED_CONTROL_TEMPLATES:
        template = ControlTemplate(**tmpl_data)
        db.add(template)
        count += 1

    await db.commit()
    print(f"  Seeded {count} extended control templates.")
