"""30 extended evidence templates for comprehensive GRC coverage."""

EXTENDED_EVIDENCE_TEMPLATES = [
    {
        "template_code": "EV-101",
        "title": "Penetration Test Report",
        "description": "Report from an internal or external penetration test including methodology, scope, findings, severity ratings, and remediation recommendations.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "annually",
        "retention_period": "3 years",
        "fields": {"sections": ["executive_summary", "scope", "methodology", "findings", "severity_ratings", "remediation_recommendations"]},
        "pass_criteria": {"test_completed": True, "critical_findings_remediated": True},
        "integrations": {"sources": ["penetration_testing_vendor"]},
    },
    {
        "template_code": "EV-102",
        "title": "Vulnerability Scan Report",
        "description": "Automated vulnerability scan results showing identified vulnerabilities, severity distribution, affected assets, and remediation status.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"sections": ["scan_summary", "severity_distribution", "affected_assets", "remediation_status", "trend_analysis"]},
        "pass_criteria": {"no_critical_over_7d": True, "no_high_over_30d": True},
        "integrations": {"sources": ["vulnerability_scanner", "cspm"]},
    },
    {
        "template_code": "EV-103",
        "title": "Patch Management Log",
        "description": "Log of all patches applied including patch ID, target systems, application date, SLA compliance, and any failed deployments.",
        "evidence_type": "log",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"columns": ["patch_id", "cve", "severity", "target_systems", "applied_date", "sla_target", "sla_met", "status"]},
        "pass_criteria": {"sla_compliance_rate": 95, "no_critical_overdue": True},
        "integrations": {"sources": ["patch_management", "wsus", "sccm"]},
    },
    {
        "template_code": "EV-104",
        "title": "Disaster Recovery Test Results",
        "description": "Documentation of disaster recovery test execution including test scenario, systems tested, actual RTO/RPO achieved, and findings.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "annually",
        "retention_period": "3 years",
        "fields": {"sections": ["test_date", "scenario", "systems_tested", "rto_target", "rto_actual", "rpo_target", "rpo_actual", "findings", "action_items"]},
        "pass_criteria": {"rto_met": True, "rpo_met": True, "test_completed": True},
        "integrations": {},
    },
    {
        "template_code": "EV-105",
        "title": "Backup Verification Report",
        "description": "Report verifying backup job completion, data integrity, and restoration capability for all critical systems.",
        "evidence_type": "report",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"columns": ["system", "backup_date", "backup_type", "size_gb", "status", "integrity_check", "restoration_tested"]},
        "pass_criteria": {"success_rate": 99, "all_critical_backed_up": True},
        "integrations": {"sources": ["backup_service", "cloud_provider"]},
    },
    {
        "template_code": "EV-106",
        "title": "Access Certification Review",
        "description": "Documentation of periodic access review showing user access rights, manager certifications, and revocation actions taken.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "semi_automated",
        "refresh_frequency": "quarterly",
        "retention_period": "2 years",
        "fields": {"sections": ["review_period", "scope", "reviewer_list", "certification_status", "revocations", "exceptions"]},
        "pass_criteria": {"review_completed": True, "all_findings_resolved": True, "completion_rate": 100},
        "integrations": {"sources": ["identity_provider", "iam_governance"]},
    },
    {
        "template_code": "EV-107",
        "title": "Security Awareness Training Records",
        "description": "Training completion records showing employee participation, scores, and compliance with mandatory security awareness training.",
        "evidence_type": "report",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "2 years",
        "fields": {"columns": ["employee_email", "department", "training_module", "assigned_date", "completion_date", "score", "status"]},
        "pass_criteria": {"completion_rate": 95, "min_score": 80},
        "integrations": {"sources": ["training_platform", "lms"]},
    },
    {
        "template_code": "EV-108",
        "title": "Third-Party Audit Report",
        "description": "Audit report from an independent third party (e.g., SOC 2 Type II, ISO 27001 surveillance audit) covering control effectiveness.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "annually",
        "retention_period": "5 years",
        "fields": {"sections": ["audit_scope", "audit_period", "opinion", "findings", "management_response", "auditor_qualifications"]},
        "pass_criteria": {"unqualified_opinion": True, "findings_addressed": True},
        "integrations": {},
    },
    {
        "template_code": "EV-109",
        "title": "Incident Response Test Results",
        "description": "Results from incident response tabletop exercises or simulations including scenario, participants, decisions, and improvement items.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "annually",
        "retention_period": "3 years",
        "fields": {"sections": ["exercise_date", "scenario_description", "participants", "timeline", "decisions_made", "findings", "improvement_actions"]},
        "pass_criteria": {"exercise_completed": True, "improvement_actions_tracked": True},
        "integrations": {},
    },
    {
        "template_code": "EV-110",
        "title": "Change Management Records",
        "description": "Records of production changes including change request, approval, implementation details, and post-change verification.",
        "evidence_type": "log",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "2 years",
        "fields": {"columns": ["change_id", "title", "requester", "approver", "risk_level", "implementation_date", "rollback_available", "verification_status"]},
        "pass_criteria": {"all_changes_approved": True, "no_unauthorized_changes": True},
        "integrations": {"sources": ["ticketing_system", "cicd_platform"]},
    },
    {
        "template_code": "EV-111",
        "title": "Network Diagram",
        "description": "Current network architecture diagram showing network segments, security zones, firewalls, load balancers, and data flows.",
        "evidence_type": "document",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "quarterly",
        "retention_period": "3 years",
        "fields": {"sections": ["network_segments", "security_zones", "firewall_placement", "data_flows", "external_connections"]},
        "pass_criteria": {"diagram_current": True, "reviewed_within_90d": True},
        "integrations": {},
    },
    {
        "template_code": "EV-112",
        "title": "Data Flow Diagram",
        "description": "Diagram showing how data moves through the organization including data sources, processing systems, storage locations, and external transfers.",
        "evidence_type": "document",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "quarterly",
        "retention_period": "3 years",
        "fields": {"sections": ["data_sources", "processing_systems", "storage_locations", "external_transfers", "encryption_points"]},
        "pass_criteria": {"diagram_current": True, "all_data_types_mapped": True},
        "integrations": {},
    },
    {
        "template_code": "EV-113",
        "title": "Risk Assessment Report",
        "description": "Comprehensive risk assessment documenting identified risks, likelihood, impact, risk scores, treatment plans, and residual risk levels.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "annually",
        "retention_period": "3 years",
        "fields": {"sections": ["assessment_scope", "methodology", "risk_inventory", "risk_ratings", "treatment_plans", "residual_risk", "risk_owner_signoff"]},
        "pass_criteria": {"assessment_completed": True, "all_risks_have_owners": True, "treatment_plans_defined": True},
        "integrations": {"sources": ["grc_platform"]},
    },
    {
        "template_code": "EV-114",
        "title": "Business Continuity Plan Document",
        "description": "Current business continuity plan document including critical process identification, continuity strategies, roles, and contact information.",
        "evidence_type": "document",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "annually",
        "retention_period": "3 years",
        "fields": {"sections": ["critical_processes", "continuity_strategies", "roles_responsibilities", "contact_lists", "activation_criteria", "recovery_procedures"]},
        "pass_criteria": {"reviewed_within_12_months": True, "contact_info_current": True},
        "integrations": {},
    },
    {
        "template_code": "EV-115",
        "title": "Privacy Impact Assessment",
        "description": "Privacy impact assessment documenting data processing activities, legal basis, privacy risks, and mitigation measures.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "as_needed",
        "retention_period": "5 years",
        "fields": {"sections": ["processing_description", "data_categories", "legal_basis", "privacy_risks", "mitigation_measures", "dpo_review"]},
        "pass_criteria": {"dpo_approved": True, "risks_mitigated": True},
        "integrations": {},
    },
    {
        "template_code": "EV-116",
        "title": "Data Retention Schedule",
        "description": "Document defining retention periods for each data category, legal basis for retention, and disposal procedures.",
        "evidence_type": "document",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "annually",
        "retention_period": "5 years",
        "fields": {"sections": ["data_categories", "retention_periods", "legal_basis", "disposal_methods", "owner_signoff"]},
        "pass_criteria": {"schedule_current": True, "all_categories_covered": True},
        "integrations": {},
    },
    {
        "template_code": "EV-117",
        "title": "Encryption Key Rotation Log",
        "description": "Log of cryptographic key rotation events including key ID, rotation date, old key disposal, and verification of new key activation.",
        "evidence_type": "log",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "2 years",
        "fields": {"columns": ["key_id", "key_type", "service", "rotation_date", "old_key_disposed", "new_key_active", "performed_by"]},
        "pass_criteria": {"all_keys_rotated_on_schedule": True, "no_expired_keys": True},
        "integrations": {"sources": ["kms", "hsm", "certificate_manager"]},
    },
    {
        "template_code": "EV-118",
        "title": "Physical Security Audit",
        "description": "Audit results for physical security controls including facility access, CCTV, environmental monitoring, and visitor management.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "annually",
        "retention_period": "3 years",
        "fields": {"sections": ["audit_scope", "access_controls", "cctv_coverage", "environmental_controls", "visitor_management", "findings", "remediation_plan"]},
        "pass_criteria": {"audit_completed": True, "critical_findings_remediated": True},
        "integrations": {},
    },
    {
        "template_code": "EV-119",
        "title": "Environmental Monitoring Report",
        "description": "Report of environmental monitoring data for data centers and server rooms including temperature, humidity, and alert incidents.",
        "evidence_type": "report",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"columns": ["location", "date", "avg_temperature_c", "avg_humidity_pct", "alerts_triggered", "incident_details"]},
        "pass_criteria": {"temp_within_range": True, "humidity_within_range": True, "no_unresolved_alerts": True},
        "integrations": {"sources": ["building_management_system", "environmental_sensors"]},
    },
    {
        "template_code": "EV-120",
        "title": "Code Review Records",
        "description": "Records of code review activities showing pull requests, reviewers, approval status, and security-related comments.",
        "evidence_type": "report",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "2 years",
        "fields": {"columns": ["pr_number", "title", "author", "reviewers", "approval_status", "security_comments", "merged_at", "branch"]},
        "pass_criteria": {"all_prs_reviewed": True, "no_self_approvals": True, "security_reviews_for_critical_changes": True},
        "integrations": {"sources": ["github", "gitlab", "bitbucket"]},
    },
    {
        "template_code": "EV-121",
        "title": "API Security Test Results",
        "description": "Results from API security testing including authentication, authorization, input validation, rate limiting, and OWASP API Top 10 coverage.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "automated",
        "refresh_frequency": "quarterly",
        "retention_period": "2 years",
        "fields": {"sections": ["api_inventory", "test_coverage", "authentication_tests", "authorization_tests", "injection_tests", "findings", "remediation_status"]},
        "pass_criteria": {"all_apis_tested": True, "no_critical_findings": True},
        "integrations": {"sources": ["dast_scanner", "api_security_tool"]},
    },
    {
        "template_code": "EV-122",
        "title": "Cloud Configuration Audit",
        "description": "Audit results of cloud infrastructure configuration against CIS Benchmarks and organizational security baselines.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"sections": ["accounts_scanned", "benchmark_version", "compliance_score", "critical_findings", "high_findings", "remediation_plan"]},
        "pass_criteria": {"compliance_score_above_90": True, "no_critical_misconfigurations": True},
        "integrations": {"sources": ["cspm", "cloud_provider"]},
    },
    {
        "template_code": "EV-123",
        "title": "Container Security Scan Results",
        "description": "Scan results for container images showing vulnerabilities, misconfigurations, and compliance with container security policies.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"sections": ["images_scanned", "vulnerability_summary", "base_image_compliance", "runtime_findings", "remediation_status"]},
        "pass_criteria": {"no_critical_vulns_in_production": True, "base_images_approved": True},
        "integrations": {"sources": ["container_registry", "container_scanner"]},
    },
    {
        "template_code": "EV-124",
        "title": "WAF/IDS Logs and Analysis",
        "description": "Web Application Firewall and Intrusion Detection System logs with analysis of blocked attacks, detected anomalies, and tuning actions.",
        "evidence_type": "log",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "1 year",
        "fields": {"columns": ["date", "source_ip", "attack_type", "rule_triggered", "action_taken", "target_url", "severity"]},
        "pass_criteria": {"waf_active": True, "ids_active": True, "rules_reviewed_quarterly": True},
        "integrations": {"sources": ["waf", "ids", "siem"]},
    },
    {
        "template_code": "EV-125",
        "title": "Security Metrics Dashboard",
        "description": "Periodic security metrics report covering KPIs such as mean time to remediate, vulnerability counts, patching rates, and incident trends.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "semi_automated",
        "refresh_frequency": "monthly",
        "retention_period": "2 years",
        "fields": {"sections": ["vulnerability_metrics", "patch_compliance", "incident_metrics", "access_review_metrics", "training_completion", "trend_analysis"]},
        "pass_criteria": {"all_kpis_reported": True, "trends_improving_or_stable": True},
        "integrations": {"sources": ["siem", "vulnerability_scanner", "ticketing_system", "grc_platform"]},
    },
    {
        "template_code": "EV-126",
        "title": "Compliance Gap Analysis",
        "description": "Analysis comparing current security posture against target framework requirements, identifying gaps and remediation priorities.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "annually",
        "retention_period": "3 years",
        "fields": {"sections": ["framework", "assessment_scope", "control_coverage", "gap_inventory", "risk_ratings", "remediation_roadmap", "executive_summary"]},
        "pass_criteria": {"assessment_completed": True, "remediation_plan_defined": True},
        "integrations": {"sources": ["grc_platform"]},
    },
    {
        "template_code": "EV-127",
        "title": "Vendor Assessment Report",
        "description": "Security assessment report for a third-party vendor including questionnaire responses, certification review, and risk rating.",
        "evidence_type": "report",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "annually",
        "retention_period": "3 years",
        "fields": {"sections": ["vendor_name", "assessment_date", "risk_tier", "questionnaire_results", "certifications", "findings", "risk_rating", "recommendation"]},
        "pass_criteria": {"assessment_completed": True, "risk_accepted_or_mitigated": True},
        "integrations": {"sources": ["vendor_management_platform"]},
    },
    {
        "template_code": "EV-128",
        "title": "SLA Compliance Report",
        "description": "Report showing vendor and internal SLA compliance metrics including uptime, response times, and security notification timeliness.",
        "evidence_type": "report",
        "format": "csv",
        "collection_method": "automated",
        "refresh_frequency": "monthly",
        "retention_period": "2 years",
        "fields": {"columns": ["vendor_name", "sla_metric", "target", "actual", "compliance_status", "period"]},
        "pass_criteria": {"overall_compliance_above_95": True, "no_critical_sla_breaches": True},
        "integrations": {"sources": ["monitoring_platform", "vendor_management_platform"]},
    },
    {
        "template_code": "EV-129",
        "title": "Data Classification Inventory",
        "description": "Inventory of data assets with classification levels, owners, storage locations, and applicable protection requirements.",
        "evidence_type": "document",
        "format": "csv",
        "collection_method": "semi_automated",
        "refresh_frequency": "quarterly",
        "retention_period": "3 years",
        "fields": {"columns": ["data_asset", "classification", "owner", "storage_location", "encryption_status", "retention_period", "access_controls"]},
        "pass_criteria": {"all_assets_classified": True, "owners_assigned": True, "protection_aligned_with_classification": True},
        "integrations": {"sources": ["data_catalog", "cloud_provider"]},
    },
    {
        "template_code": "EV-130",
        "title": "Security Architecture Review",
        "description": "Review of security architecture covering network design, defense-in-depth layers, trust boundaries, and alignment with security requirements.",
        "evidence_type": "document",
        "format": "pdf",
        "collection_method": "manual",
        "refresh_frequency": "annually",
        "retention_period": "3 years",
        "fields": {"sections": ["architecture_overview", "trust_boundaries", "defense_layers", "threat_model", "security_controls_mapping", "recommendations"]},
        "pass_criteria": {"review_completed": True, "recommendations_tracked": True},
        "integrations": {},
    },
]


async def seed_extended_evidence_templates(db):
    """Seed 30 extended evidence templates."""
    from app.models.evidence_template import EvidenceTemplate
    from sqlalchemy import select

    # Check if any of these templates already exist
    existing = await db.execute(
        select(EvidenceTemplate).where(EvidenceTemplate.template_code == "EV-101")
    )
    if existing.scalar_one_or_none():
        print("  -> Extended evidence templates already seeded, skipping.")
        return

    count = 0
    for tmpl_data in EXTENDED_EVIDENCE_TEMPLATES:
        template = EvidenceTemplate(**tmpl_data)
        db.add(template)
        count += 1

    await db.commit()
    print(f"  Seeded {count} extended evidence templates.")
